name: micit
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.8
  adaptive_theme: ^3.6.0
  equatable: ^2.0.7
  either_dart: ^1.0.0
  logger: ^2.5.0
  dio: ^5.7.0
  get_it: ^8.0.2
  injectable: ^2.5.0
  build_runner: ^2.4.13
  pretty_dio_logger: ^1.4.0
  go_router: ^14.6.2
  flutter_smart_dialog: ^4.9.8+5
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  flutter_bloc: ^8.1.6
  injectable_generator: ^2.6.2
  firebase_core: ^3.8.1
  google_sign_in: ^6.2.2
  firebase_auth: ^5.3.4
  flutter_spinkit: ^5.2.1
  rename_app: ^1.6.1
  icons_launcher: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - assets/contacts_icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsLight.ttf
          weight: 300
    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400