// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA73NL9gZopNZwpBZ3Y9c5oljuKQ-teaVA',
    appId: '1:695200015194:web:31837720f8e1958ad78963',
    messagingSenderId: '695200015194',
    projectId: 'micit-b0a5e',
    authDomain: 'micit-b0a5e.firebaseapp.com',
    storageBucket: 'micit-b0a5e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy0swpyJV45mWYth5iGnIeyDvI9epH3tE',
    appId: '1:695200015194:android:c1b79384069e1457d78963',
    messagingSenderId: '695200015194',
    projectId: 'micit-b0a5e',
    storageBucket: 'micit-b0a5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmV2Tlx80_HlmdLPXFQGXeeyl6UFWFeY8',
    appId: '1:695200015194:ios:9bd9a352d96c9cd3d78963',
    messagingSenderId: '695200015194',
    projectId: 'micit-b0a5e',
    storageBucket: 'micit-b0a5e.firebasestorage.app',
    iosBundleId: 'com.micit.micit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmV2Tlx80_HlmdLPXFQGXeeyl6UFWFeY8',
    appId: '1:695200015194:ios:9bd9a352d96c9cd3d78963',
    messagingSenderId: '695200015194',
    projectId: 'micit-b0a5e',
    storageBucket: 'micit-b0a5e.firebasestorage.app',
    iosBundleId: 'com.micit.micit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA73NL9gZopNZwpBZ3Y9c5oljuKQ-teaVA',
    appId: '1:695200015194:web:c80a65f9b05034f9d78963',
    messagingSenderId: '695200015194',
    projectId: 'micit-b0a5e',
    authDomain: 'micit-b0a5e.firebaseapp.com',
    storageBucket: 'micit-b0a5e.firebasestorage.app',
  );
}
